spring:
  application:
    name: ods-eureka-service
  security:
    user:
      name: ${EUREKA_USER:admin}
      password: ${EUREKA_PASS:admin}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8090
management:
  endpoint:
    env:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_BACKUP_URI:localhost}:${EUREKA_BACKUP_PORT:8090}/eureka
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 5
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      user.name: ${BOOT_ADMIN_USER:default}
      user.password: ${BOOT_ADMIN_PASS:default}
  server:
    a-w-s-access-id: ${AWS_ACCESS_KEY}
    a-w-s-secret-key: ${AWS_SECRET_KEY}
    eviction-interval-timer-in-ms: 10000
